### ISSUE TITLE
这个东西支持B服吗？

### ISSUE THREAD

**Issue by xiao-gy** [Tao0Lu/Arknights_Anti-addiction_Cheater#10]

**Comment by JeffersonQin** [comment]
支持的吧

**Comment by Tao0Lu** [comment]
> 支持的吧

不支持啊，b服的fcm是用的b站给的 sdk ，cgi 是 line3-realtime-api.biligame.net/app/v2/time/heartbeat
这玩意是有签名一系列认证的，可以试试 frida 找一下算法

**Comment by JeffersonQin** [comment]
啊 dbq 记错了（可能之前帮b服的抓包的时候没把之前的记录删掉混起来了🤣（我自裁

**Comment by xiao-gy** [comment]
可还行


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月30日 10:28:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tao0Lu/Arknights_Anti-addiction_Cheater] 这个东西支持B服吗？ (#10)




 
啊 dbq 记错了（可能之前帮b服的抓包的时候没把之前的记录删掉混起来了🤣（我自裁
