### ISSUE TITLE
azur lane plz

### ISSUE THREAD

**Issue by Enaium** [Tao0Lu/Arknights_Anti-addiction_Cheater#11]
azur lane plz

**Comment by Enaium** [comment]
解决了 做了个解实名认证的

**Comment by long45343** [comment]
> 解决了 做了个解实名认证的

？？？
还有这等操作？

**Comment by Enaium** [comment]
> 
> 
> > 解决了 做了个解实名认证的
> 
> ？？？
> 还有这等操作？

原理就是获取实名的时候有个请求返回值 是否实名的值 改为没实名 就会让你填名字和身份证

**Comment by Enaium** [comment]
> 
> 
> > 解决了 做了个解实名认证的
> 
> ？？？
> 还有这等操作？

https://github.com/Enaium/BiligameRemoveRealnameVerified 源码
