### ISSUE TITLE
IOS端进入游戏界面请求应修改

### ISSUE THREAD

**Issue by bbaa-bbaa** [Tao0Lu/Arknights_Anti-addiction_Cheater#12]
现在好像看不到ak-fs.hypergryph.com的请求了
https://ak-fs.hypergryph.com/announce/IOS/preannouncement.meta.json 疑应改为 https://ak-conf.hypergryph.com/config/prod/announce_meta/IOS/preannouncement.meta.json
无安卓设备不知道安卓是否也要修改
大佬有空看下？

**Comment by Tao0Lu** [comment]
是的，这个请求修改后会出现10点后无法退出游戏重进的bug。

**Comment by bbaa-bbaa** [comment]
Fixed in https://github.com/Tao0Lu/Arknights_Anti-addiction_Cheater/blob/83e9b46d216e27d567bb70e7c4489947a1feacfb/fcm.py#L64
