### ISSUE TITLE
20210831更新后本项目是否会继续更新？

### ISSUE THREAD

**Issue by SpiritedAwayCN** [Tao0Lu/Arknights_Anti-addiction_Cheater#14]
2021年8月31日fcm系统更新，肯定会有变化

如果还是用先前获取剩余时间来判断能否登入的话，篡改json的方法依然有效，只是需要分析一下网络包小改一下代码

但目前尚不清楚认证机制是否会大改，想请问下作者是否有继续维护此项目的意向，感谢！

**Comment by SpiritedAwayCN** [comment]
已确认无需修改依然可用，万分感谢！

**Comment by Zheizh** [comment]
请教一下大佬我这个限时时间段外进去显示获取网络配置失败怎么解决，谢谢！

**Comment by SpiritedAwayCN** [comment]
> 请教一下大佬我这个限时时间段外进去显示获取网络配置失败怎么解决，谢谢！

如果是Andriod版本不到7，建议检查模拟器的网络环境；如果不低于7，很可能是证书问题，在项目网站有解决方法。

**Comment by Zheizh** [comment]
em我这是ios的  我试着运行了一下那个fcm.py然后报错no module named mitmproxy  这个是证书吗

**Comment by SpiritedAwayCN** [comment]
> em我这是ios的 我试着运行了一下那个fcm.py然后报错no module named mitmproxy 这个是证书吗

不是去跑那个python，release里面的压缩包给了启动命令

**Comment by Zheizh** [comment]
那是手机里面下的那个文件吗 那个我都按照步骤来了

**Comment by Zheizh** [comment]
啊谢谢大佬我全部重搞了一遍就可以了

**Comment by Zheizh** [comment]
方便来个好友吗 ：）

**Comment by SpiritedAwayCN** [comment]
> 方便来个好友吗 ：）

官服 NekoSACN#7128
2203蓝毒(1) 2403山(2)  2423煌(2)
是个成年的账号，只是帮我的朋友逃过fcm。

**Comment by Zheizh** [comment]
加了加了 ：D

**Comment by SpiritedAwayCN** [comment]
> 加了加了 ：D

已同意，祝玩得愉快！

**Comment by Zheizh** [comment]
谢啦
