### ISSUE TITLE
脚本不能使用了？

### ISSUE THREAD

**Issue by leisiyu1** [Tao0Lu/Arknights_Anti-addiction_Cheater#15]
现在会
返回网络异常，登陆失败，请稍后重试。
错误号0

**Comment by leisiyu1** [comment]
这个脚本是只能越过时间限制而不能在非登录时间登录吗？

**Comment by DecoratorGeorge** [comment]
网络异常应该去掉make404就行

**Comment by Zheizh** [comment]
> 网络异常应该去掉make404就行

请问大佬是去掉      flow.response = http.HTTPResponse.make(404)      这个else吗

**Comment by ayanonanami** [comment]
刚用，想问一下有封号的风险吗？或者迄今为止有没有被封的

**Comment by DecoratorGeorge** [comment]
> > 网络异常应该去掉make404就行
> 
> 请问大佬是去掉 flow.response = http.HTTPResponse.make(404) 这个else吗

是的，现在新脚本应该已经去掉了
