### ISSUE TITLE
电脑渣求助。。。

### ISSUE THREAD

**Issue by Zheizh** [Tao0Lu/Arknights_Anti-addiction_Cheater#19]
试了很多遍但是进游戏就显示 获取网络配置失败
请问大佬我这怎么解决

**Comment by DargonXuan** [comment]
如果你是官服：
- 请将最新脚本中67~69行删除后运行。

- 或者clone我的仓库https://github.com/DargonXuan/arknights-anti-addiction-cheater/tree/public-network
  安装好依赖
  仓库路径下运行
  ```shell
  mitmdump -s fcm-nobilibli.py --listen-host 0.0.0.0 --listen-port 8088
  ```
