### ISSUE TITLE
能够做一个在手机上用的版本吗

### ISSUE THREAD

**Issue by long45343** [Tao0Lu/Arknights_Anti-addiction_Cheater#4]
手机不太方便的一说

**Comment by Tao0Lu** [comment]
首先抱歉这么久没有回复这条issue。收到issue的时候找了很久还是没有搞出一个在手机上能较好运行的方法，之后慢慢地就放弃了，忘了还有这一件事。
刚刚看到了 [MengLuwa/ArkNightsForMinor](https://github.com/MengLuwa/ArkNightsForMinor) 这个不错的项目，我想能不能复活这一项目。
幸运的是，YJ没有改api，只要改一下offset就成功了！
[Tao0Lu/ArkNightsForMinor](https://github.com/Tao0Lu/ArkNightsForMinor)

**Comment by long45343** [comment]
> 首先抱歉这么久没有回复这条issue。收到issue的时候找了很久还是没有搞出一个在手机上能较好运行的方法，之后慢慢地就放弃了，忘了还有这一件事。
> 刚刚看到了 [MengLuwa/ArkNightsForMinor](https://github.com/MengLuwa/ArkNightsForMinor) 这个不错的项目，我想能不能复活这一项目。
> 幸运的是，YJ没有改api，只要改一下offset就成功了！
> [Tao0Lu/ArkNightsForMinor](https://github.com/Tao0Lu/ArkNightsForMinor)

万分感谢！
可是为什么在arm设备上无法运行？

**Comment by Tao0Lu** [comment]
> > 首先抱歉这么久没有回复这条issue。收到issue的时候找了很久还是没有搞出一个在手机上能较好运行的方法，之后慢慢地就放弃了，忘了还有这一件事。
> > 刚刚看到了 [MengLuwa/ArkNightsForMinor](https://github.com/MengLuwa/ArkNightsForMinor) 这个不错的项目，我想能不能复活这一项目。
> > 幸运的是，YJ没有改api，只要改一下offset就成功了！
> > [Tao0Lu/ArkNightsForMinor](https://github.com/Tao0Lu/ArkNightsForMinor)
> 
> 万分感谢！
> 可是为什么在arm设备上无法运行？

kusa，才发现，arm和x86下的offset是不一样的，也就是说原作者的apk在x86是不能运行的(试了，的确是的)。

**Comment by long45343** [comment]
那麻烦一下可以改吗？小白不会2333333

**Comment by Tao0Lu** [comment]
> 那麻烦一下可以改吗？小白不会2333333

仓库和百度盘早更新了啊？！

**Comment by long45343** [comment]
> > 那麻烦一下可以改吗？小白不会2333333
> 
> 仓库和百度盘早更新了啊？！

sorry，没看到，万分抱歉...
